import { AlternateURLs } from "next/dist/lib/metadata/types/alternative-urls-types";
import { BOT_LOCALE } from "./constants";
import { CountryMap } from "./types";

export const COUNTRIES: CountryMap = {
    af: ["Afghanistan", "AFN", "؋", "93", "🇦🇫"],
    ax: ["Aland Islands", "EUR", "€", "+358-18", "🇦🇽"],
    al: ["Albania", "ALL", "Lek", "355", "🇦🇱"],
    dz: ["Algeria", "DZD", "دج", "213", "🇩🇿"],
    as: ["American Samoa", "USD", "$", "+1-684", "🇦🇸"],
    ad: ["Andorra", "EUR", "€", "376", "🇦🇩"],
    ao: ["Angola", "AOA", "Kz", "244", "🇦🇴"],
    ai: ["Anguilla", "XCD", "$", "+1-264", "🇦🇮"],
    aq: ["Antarctica", "AAD", "$", "672", "🇦🇶"],
    ag: ["Antigua And Barbuda", "XCD", "$", "+1-268", "🇦🇬"],
    ar: ["Argentina", "ARS", "$", "54", "🇦🇷"],
    am: ["Armenia", "AMD", "֏", "374", "🇦🇲"],
    aw: ["Aruba", "AWG", "ƒ", "297", "🇦🇼"],
    au: ["Australia", "AUD", "$", "61", "🇦🇺"],
    at: ["Austria", "EUR", "€", "43", "🇦🇹"],
    az: ["Azerbaijan", "AZN", "m", "994", "🇦🇿"],
    bh: ["Bahrain", "BHD", ".د.ب", "973", "🇧🇭"],
    bd: ["Bangladesh", "BDT", "৳", "880", "🇧🇩"],
    bb: ["Barbados", "BBD", "Bds$", "+1-246", "🇧🇧"],
    by: ["Belarus", "BYN", "Br", "375", "🇧🇾"],
    be: ["Belgium", "EUR", "€", "32", "🇧🇪"],
    bz: ["Belize", "BZD", "$", "501", "🇧🇿"],
    bj: ["Benin", "XOF", "CFA", "229", "🇧🇯"],
    bm: ["Bermuda", "BMD", "$", "+1-441", "🇧🇲"],
    bt: ["Bhutan", "BTN", "Nu.", "975", "🇧🇹"],
    bo: ["Bolivia", "BOB", "Bs.", "591", "🇧🇴"],
    bq: ["Bonaire, Sint Eustatius and Saba", "USD", "$", "599", "🇧🇶"],
    ba: ["Bosnia and Herzegovina", "BAM", "KM", "387", "🇧🇦"],
    bw: ["Botswana", "BWP", "P", "267", "🇧🇼"],
    bv: ["Bouvet Island", "NOK", "kr", "0055", "🇧🇻"],
    br: ["Brazil", "BRL", "R$", "55", "🇧🇷"],
    io: ["British Indian Ocean Territory", "USD", "$", "246", "🇮🇴"],
    bn: ["Brunei", "BND", "B$", "673", "🇧🇳"],
    bg: ["Bulgaria", "BGN", "Лв.", "359", "🇧🇬"],
    bf: ["Burkina Faso", "XOF", "CFA", "226", "🇧🇫"],
    bi: ["Burundi", "BIF", "FBu", "257", "🇧🇮"],
    kh: ["Cambodia", "KHR", "KHR", "855", "🇰🇭"],
    cm: ["Cameroon", "XAF", "FCFA", "237", "🇨🇲"],
    ca: ["Canada", "CAD", "$", "1", "🇨🇦"],
    cv: ["Cape Verde", "CVE", "$", "238", "🇨🇻"],
    ky: ["Cayman Islands", "KYD", "$", "+1-345", "🇰🇾"],
    cf: ["Central African Republic", "XAF", "FCFA", "236", "🇨🇫"],
    td: ["Chad", "XAF", "FCFA", "235", "🇹🇩"],
    cl: ["Chile", "CLP", "$", "56", "🇨🇱"],
    cn: ["China", "CNY", "¥", "86", "🇨🇳"],
    cx: ["Christmas Island", "AUD", "$", "61", "🇨🇽"],
    cc: ["Cocos (Keeling) Islands", "AUD", "$", "61", "🇨🇨"],
    co: ["Colombia", "COP", "$", "57", "🇨🇴"],
    km: ["Comoros", "KMF", "CF", "269", "🇰🇲"],
    cg: ["Congo", "XAF", "FC", "242", "🇨🇬"],
    ck: ["Cook Islands", "NZD", "$", "682", "🇨🇰"],
    cr: ["Costa Rica", "CRC", "₡", "506", "🇨🇷"],
    ci: ["Cote D'Ivoire (Ivory Coast)", "XOF", "CFA", "225", "🇨🇮"],
    hr: ["Croatia", "HRK", "kn", "385", "🇭🇷"],
    cu: ["Cuba", "CUP", "$", "53", "🇨🇺"],
    cw: ["Curaçao", "ANG", "ƒ", "599", "🇨🇼"],
    cy: ["Cyprus", "EUR", "€", "357", "🇨🇾"],
    cz: ["Czech Republic", "CZK", "Kč", "420", "🇨🇿"],
    cd: ["Democratic Republic of the Congo", "CDF", "FC", "243", "🇨🇩"],
    dk: ["Denmark", "DKK", "Kr.", "45", "🇩🇰"],
    dj: ["Djibouti", "DJF", "Fdj", "253", "🇩🇯"],
    dm: ["Dominica", "XCD", "$", "+1-767", "🇩🇲"],
    do: ["Dominican Republic", "DOP", "$", "+1-809 and 1-829", "🇩🇴"],
    tl: ["East Timor", "USD", "$", "670", "🇹🇱"],
    ec: ["Ecuador", "USD", "$", "593", "🇪🇨"],
    eg: ["Egypt", "EGP", "ج.م", "20", "🇪🇬"],
    sv: ["El Salvador", "USD", "$", "503", "🇸🇻"],
    gq: ["Equatorial Guinea", "XAF", "FCFA", "240", "🇬🇶"],
    er: ["Eritrea", "ERN", "Nfk", "291", "🇪🇷"],
    ee: ["Estonia", "EUR", "€", "372", "🇪🇪"],
    et: ["Ethiopia", "ETB", "Nkf", "251", "🇪🇹"],
    fk: ["Falkland Islands", "FKP", "£", "500", "🇫🇰"],
    fo: ["Faroe Islands", "DKK", "Kr.", "298", "🇫🇴"],
    fj: ["Fiji Islands", "FJD", "FJ$", "679", "🇫🇯"],
    fi: ["Finland", "EUR", "€", "358", "🇫🇮"],
    fr: ["France", "EUR", "€", "33", "🇫🇷"],
    gf: ["French Guiana", "EUR", "€", "594", "🇬🇫"],
    pf: ["French Polynesia", "XPF", "₣", "689", "🇵🇫"],
    tf: ["French Southern Territories", "EUR", "€", "262", "🇹🇫"],
    ga: ["Gabon", "XAF", "FCFA", "241", "🇬🇦"],
    gm: ["Gambia The", "GMD", "D", "220", "🇬🇲"],
    ge: ["Georgia", "GEL", "ლ", "995", "🇬🇪"],
    de: ["Germany", "EUR", "€", "49", "🇩🇪"],
    gh: ["Ghana", "GHS", "GH₵", "233", "🇬🇭"],
    gi: ["Gibraltar", "GIP", "£", "350", "🇬🇮"],
    gr: ["Greece", "EUR", "€", "30", "🇬🇷"],
    gl: ["Greenland", "DKK", "Kr.", "299", "🇬🇱"],
    gd: ["Grenada", "XCD", "$", "+1-473", "🇬🇩"],
    gp: ["Guadeloupe", "EUR", "€", "590", "🇬🇵"],
    gu: ["Guam", "USD", "$", "+1-671", "🇬🇺"],
    gt: ["Guatemala", "GTQ", "Q", "502", "🇬🇹"],
    gg: ["Guernsey and Alderney", "GBP", "£", "+44-1481", "🇬🇬"],
    gn: ["Guinea", "GNF", "FG", "224", "🇬🇳"],
    gw: ["Guinea-Bissau", "XOF", "CFA", "245", "🇬🇼"],
    gy: ["Guyana", "GYD", "$", "592", "🇬🇾"],
    ht: ["Haiti", "HTG", "G", "509", "🇭🇹"],
    hm: ["Heard Island and McDonald Islands", "AUD", "$", "672", "🇭🇲"],
    hn: ["Honduras", "HNL", "L", "504", "🇭🇳"],
    hk: ["Hong Kong S.A.R.", "HKD", "$", "852", "🇭🇰"],
    hu: ["Hungary", "HUF", "Ft", "36", "🇭🇺"],
    is: ["Iceland", "ISK", "kr", "354", "🇮🇸"],
    in: ["India", "INR", "₹", "91", "🇮🇳"],
    id: ["Indonesia", "IDR", "Rp", "62", "🇮🇩"],
    ir: ["Iran", "IRR", "﷼", "98", "🇮🇷"],
    iq: ["Iraq", "IQD", "د.ع", "964", "🇮🇶"],
    ie: ["Ireland", "EUR", "€", "353", "🇮🇪"],
    il: ["Israel", "ILS", "₪", "972", "🇮🇱"],
    it: ["Italy", "EUR", "€", "39", "🇮🇹"],
    jm: ["Jamaica", "JMD", "J$", "+1-876", "🇯🇲"],
    jp: ["Japan", "JPY", "¥", "81", "🇯🇵"],
    je: ["Jersey", "GBP", "£", "+44-1534", "🇯🇪"],
    jo: ["Jordan", "JOD", "ا.د", "962", "🇯🇴"],
    kz: ["Kazakhstan", "KZT", "лв", "7", "🇰🇿"],
    ke: ["Kenya", "KES", "KSh", "254", "🇰🇪"],
    ki: ["Kiribati", "AUD", "$", "686", "🇰🇮"],
    xk: ["Kosovo", "EUR", "€", "383", "🇽🇰"],
    kw: ["Kuwait", "KWD", "ك.د", "965", "🇰🇼"],
    kg: ["Kyrgyzstan", "KGS", "лв", "996", "🇰🇬"],
    la: ["Laos", "LAK", "₭", "856", "🇱🇦"],
    lv: ["Latvia", "EUR", "€", "371", "🇱🇻"],
    lb: ["Lebanon", "LBP", "£", "961", "🇱🇧"],
    ls: ["Lesotho", "LSL", "L", "266", "🇱🇸"],
    lr: ["Liberia", "LRD", "$", "231", "🇱🇷"],
    ly: ["Libya", "LYD", "د.ل", "218", "🇱🇾"],
    li: ["Liechtenstein", "CHF", "CHf", "423", "🇱🇮"],
    lt: ["Lithuania", "EUR", "€", "370", "🇱🇹"],
    lu: ["Luxembourg", "EUR", "€", "352", "🇱🇺"],
    mo: ["Macau S.A.R.", "MOP", "$", "853", "🇲🇴"],
    mg: ["Madagascar", "MGA", "Ar", "261", "🇲🇬"],
    mw: ["Malawi", "MWK", "MK", "265", "🇲🇼"],
    my: ["Malaysia", "MYR", "RM", "60", "🇲🇾"],
    mv: ["Maldives", "MVR", "Rf", "960", "🇲🇻"],
    ml: ["Mali", "XOF", "CFA", "223", "🇲🇱"],
    mt: ["Malta", "EUR", "€", "356", "🇲🇹"],
    im: ["Man (Isle of)", "GBP", "£", "+44-1624", "🇮🇲"],
    mh: ["Marshall Islands", "USD", "$", "692", "🇲🇭"],
    mq: ["Martinique", "EUR", "€", "596", "🇲🇶"],
    mr: ["Mauritania", "MRO", "MRU", "222", "🇲🇷"],
    mu: ["Mauritius", "MUR", "₨", "230", "🇲🇺"],
    yt: ["Mayotte", "EUR", "€", "262", "🇾🇹"],
    mx: ["Mexico", "MXN", "$", "52", "🇲🇽"],
    fm: ["Micronesia", "USD", "$", "691", "🇫🇲"],
    md: ["Moldova", "MDL", "L", "373", "🇲🇩"],
    mc: ["Monaco", "EUR", "€", "377", "🇲🇨"],
    mn: ["Mongolia", "MNT", "₮", "976", "🇲🇳"],
    me: ["Montenegro", "EUR", "€", "382", "🇲🇪"],
    ms: ["Montserrat", "XCD", "$", "+1-664", "🇲🇸"],
    ma: ["Morocco", "MAD", "DH", "212", "🇲🇦"],
    mz: ["Mozambique", "MZN", "MT", "258", "🇲🇿"],
    mm: ["Myanmar", "MMK", "K", "95", "🇲🇲"],
    na: ["Namibia", "NAD", "$", "264", "🇳🇦"],
    nr: ["Nauru", "AUD", "$", "674", "🇳🇷"],
    np: ["Nepal", "NPR", "₨", "977", "🇳🇵"],
    nl: ["Netherlands", "EUR", "€", "31", "🇳🇱"],
    nc: ["New Caledonia", "XPF", "₣", "687", "🇳🇨"],
    nz: ["New Zealand", "NZD", "$", "64", "🇳🇿"],
    ni: ["Nicaragua", "NIO", "C$", "505", "🇳🇮"],
    ne: ["Niger", "XOF", "CFA", "227", "🇳🇪"],
    ng: ["Nigeria", "NGN", "₦", "234", "🇳🇬"],
    nu: ["Niue", "NZD", "$", "683", "🇳🇺"],
    nf: ["Norfolk Island", "AUD", "$", "672", "🇳🇫"],
    kp: ["North Korea", "KPW", "₩", "850", "🇰🇵"],
    mk: ["North Macedonia", "MKD", "ден", "389", "🇲🇰"],
    mp: ["Northern Mariana Islands", "USD", "$", "+1-670", "🇲🇵"],
    no: ["Norway", "NOK", "kr", "47", "🇳🇴"],
    om: ["Oman", "OMR", ".ع.ر", "968", "🇴🇲"],
    pk: ["Pakistan", "PKR", "₨", "92", "🇵🇰"],
    pw: ["Palau", "USD", "$", "680", "🇵🇼"],
    ps: ["Palestinian Territory Occupied", "ILS", "₪", "970", "🇵🇸"],
    pa: ["Panama", "PAB", "B/.", "507", "🇵🇦"],
    pg: ["Papua new Guinea", "PGK", "K", "675", "🇵🇬"],
    py: ["Paraguay", "PYG", "₲", "595", "🇵🇾"],
    pe: ["Peru", "PEN", "S/.", "51", "🇵🇪"],
    ph: ["Philippines", "PHP", "₱", "63", "🇵🇭"],
    pn: ["Pitcairn Island", "NZD", "$", "870", "🇵🇳"],
    pl: ["Poland", "PLN", "zł", "48", "🇵🇱"],
    pt: ["Portugal", "EUR", "€", "351", "🇵🇹"],
    pr: ["Puerto Rico", "USD", "$", "+1-787 and 1-939", "🇵🇷"],
    qa: ["Qatar", "QAR", "ق.ر", "974", "🇶🇦"],
    re: ["Reunion", "EUR", "€", "262", "🇷🇪"],
    ro: ["Romania", "RON", "lei", "40", "🇷🇴"],
    ru: ["Russia", "RUB", "₽", "7", "🇷🇺"],
    rw: ["Rwanda", "RWF", "FRw", "250", "🇷🇼"],
    sh: ["Saint Helena", "SHP", "£", "290", "🇸🇭"],
    kn: ["Saint Kitts And Nevis", "XCD", "$", "+1-869", "🇰🇳"],
    lc: ["Saint Lucia", "XCD", "$", "+1-758", "🇱🇨"],
    pm: ["Saint Pierre and Miquelon", "EUR", "€", "508", "🇵🇲"],
    vc: ["Saint Vincent And The Grenadines", "XCD", "$", "+1-784", "🇻🇨"],
    bl: ["Saint-Barthelemy", "EUR", "€", "590", "🇧🇱"],
    mf: ["Saint-Martin (French part)", "EUR", "€", "590", "🇲🇫"],
    ws: ["Samoa", "WST", "SAT", "685", "🇼🇸"],
    sm: ["San Marino", "EUR", "€", "378", "🇸🇲"],
    st: ["Sao Tome and Principe", "STD", "Db", "239", "🇸🇹"],
    sa: ["Saudi Arabia", "SAR", "﷼", "966", "🇸🇦"],
    sn: ["Senegal", "XOF", "CFA", "221", "🇸🇳"],
    rs: ["Serbia", "RSD", "din", "381", "🇷🇸"],
    sc: ["Seychelles", "SCR", "SRe", "248", "🇸🇨"],
    sl: ["Sierra Leone", "SLL", "Le", "232", "🇸🇱"],
    sg: ["Singapore", "SGD", "$", "65", "🇸🇬"],
    sx: ["Sint Maarten (Dutch part)", "ANG", "ƒ", "1721", "🇸🇽"],
    sk: ["Slovakia", "EUR", "€", "421", "🇸🇰"],
    si: ["Slovenia", "EUR", "€", "386", "🇸🇮"],
    sb: ["Solomon Islands", "SBD", "Si$", "677", "🇸🇧"],
    so: ["Somalia", "SOS", "Sh.so.", "252", "🇸🇴"],
    za: ["South Africa", "ZAR", "R", "27", "🇿🇦"],
    gs: ["South Georgia", "GBP", "£", "500", "🇬🇸"],
    kr: ["South Korea", "KRW", "₩", "82", "🇰🇷"],
    ss: ["South Sudan", "SSP", "£", "211", "🇸🇸"],
    es: ["Spain", "EUR", "€", "34", "🇪🇸"],
    lk: ["Sri Lanka", "LKR", "Rs", "94", "🇱🇰"],
    sd: ["Sudan", "SDG", ".س.ج", "249", "🇸🇩"],
    sr: ["Suriname", "SRD", "$", "597", "🇸🇷"],
    sj: ["Svalbard And Jan Mayen Islands", "NOK", "kr", "47", "🇸🇯"],
    sz: ["Swaziland", "SZL", "E", "268", "🇸🇿"],
    se: ["Sweden", "SEK", "kr", "46", "🇸🇪"],
    ch: ["Switzerland", "CHF", "CHf", "41", "🇨🇭"],
    sy: ["Syria", "SYP", "LS", "963", "🇸🇾"],
    tw: ["Taiwan", "TWD", "$", "886", "🇹🇼"],
    tj: ["Tajikistan", "TJS", "SM", "992", "🇹🇯"],
    tz: ["Tanzania", "TZS", "TSh", "255", "🇹🇿"],
    th: ["Thailand", "THB", "฿", "66", "🇹🇭"],
    bs: ["The Bahamas", "BSD", "B$", "+1-242", "🇧🇸"],
    tg: ["Togo", "XOF", "CFA", "228", "🇹🇬"],
    tk: ["Tokelau", "NZD", "$", "690", "🇹🇰"],
    to: ["Tonga", "TOP", "$", "676", "🇹🇴"],
    tt: ["Trinidad And Tobago", "TTD", "$", "+1-868", "🇹🇹"],
    tn: ["Tunisia", "TND", "ت.د", "216", "🇹🇳"],
    tr: ["Turkey", "TRY", "₺", "90", "🇹🇷"],
    tm: ["Turkmenistan", "TMT", "T", "993", "🇹🇲"],
    tc: ["Turks And Caicos Islands", "USD", "$", "+1-649", "🇹🇨"],
    tv: ["Tuvalu", "AUD", "$", "688", "🇹🇻"],
    ug: ["Uganda", "UGX", "USh", "256", "🇺🇬"],
    ua: ["Ukraine", "UAH", "₴", "380", "🇺🇦"],
    ae: ["United Arab Emirates", "AED", "إ.د", "971", "🇦🇪"],
    gb: ["United Kingdom", "GBP", "£", "44", "🇬🇧"],
    us: ["United States", "USD", "$", "1", "🇺🇸"],
    um: ["United States Minor Outlying Islands", "USD", "$", "1", "🇺🇲"],
    uy: ["Uruguay", "UYU", "$", "598", "🇺🇾"],
    uz: ["Uzbekistan", "UZS", "лв", "998", "🇺🇿"],
    vu: ["Vanuatu", "VUV", "VT", "678", "🇻🇺"],
    va: ["Vatican City State (Holy See)", "EUR", "€", "379", "🇻🇦"],
    ve: ["Venezuela", "VES", "Bs", "58", "🇻🇪"],
    vn: ["Vietnam", "VND", "₫", "84", "🇻🇳"],
    vg: ["Virgin Islands (British)", "USD", "$", "+1-284", "🇻🇬"],
    vi: ["Virgin Islands (US)", "USD", "$", "+1-340", "🇻🇮"],
    wf: ["Wallis And Futuna Islands", "XPF", "₣", "681", "🇼🇫"],
    eh: ["Western Sahara", "MAD", "MAD", "212", "🇪🇭"],
    ye: ["Yemen", "YER", "﷼", "967", "🇾🇪"],
    zm: ["Zambia", "ZMW", "ZK", "260", "🇿🇲"],
    zw: ["Zimbabwe", "ZWL", "$", "263", "🇿🇼"],
};

export const getAlternativeLinks = (link: string): AlternateURLs => {
    const languages: { [key: string]: string } = {};
    Object.keys(COUNTRIES).forEach((key) => {
        languages[`en-${key.toLowerCase()}`] = `/${key}${link}`;
    });
    languages["x-default"] = `/${BOT_LOCALE}${link}`;

    return {
        canonical: `/${BOT_LOCALE}${link}`,
        languages,
    };
};
