/** Get list of features for listing form and filters */
export const VEHICLE_FEATURES = [
    "Air Conditioning",
    "Electric Seats",
    "Heated Seats",
    "Lane Assist",
    "Park Assist",
    "Power Mirror",
    "Power Steering",
    "Power Window",
    "Push Start",
    "Reverse Camera",
    "SRS Air Bags",
    "Sunroof",
    "Traction Control",
    "Bluetooth Connectivity",
    "Blind Spot Monitoring",
    "Adaptive Cruise Control",
    "Automatic Emergency Braking",
    "Keyless Entry with Remote Start",
    "Wireless Charging",
    "360-Degree Camera System",
    "Driver's Seat Memory Settings",
    "Rain-Sensing Wipers",
    "Heated Steering Wheel",
    "Ventilated/Cooled Seats",
    "Multi-Zone Climate Control",
    "Collision Mitigation System",
    "Traffic Sign Recognition",
];
