import { Toaster } from "react-hot-toast";
import { ScrollToTop } from "@/components/Common/ScrollToTop";
import { Footer } from "@/components/Footer";
import { NavBar } from "@/components/NavBar";
import { ReactQueryProvider } from "@/providers/query-provider";
import { ChildrenProps } from "@/utils/types";
import { standardFont } from "./fonts";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
    return (
        <html lang="en">
            <body className={standardFont.className}>
                <ScrollToTop />
                <Toaster position="bottom-right" toastOptions={{ error: { duration: 10000 }, duration: 5000 }} />
                <ReactQueryProvider>
                    <NavBar />
                    <main>{children}</main>
                    <Footer />
                </ReactQueryProvider>
            </body>
        </html>
    );
}
