###############
# Run in Dev  #
###############

# Using devbox as base build image
FROM jetpackio/devbox:latest AS build-stage

# Installing your devbox project
WORKDIR /code
RUN mkdir -p /code && chown ${DEVBOX_USER}:${DEVBOX_USER} /code
USER ${DEVBOX_USER}:${DEVBOX_USER}
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} devbox.json devbox.json
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} devbox.lock devbox.lock
RUN devbox install
USER root:root

# Copy core files
COPY package.json nx.json pnpm-* go.* ./
COPY apps/webapp/package.json apps/webapp/pnpm-* apps/webapp/
COPY libs/protos libs/protos

# Install dependencies
RUN devbox run pnpm install --frozen-lockfile

# Copy the apps/webapp directories
COPY apps/webapp apps/webapp

# Set necessary build-time variables as args
# Public env as args
ARG NEXT_PUBLIC_SUPPORT_EMAIL

# Set args as public env variables
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL
# Private temporary env variables (Will be overriden during runtime via runtime variables)
ENV GRPC_API_BASE_URL 'http://localhost:50051'
ENV AUTH0_BASE_URL 'http://localhost:3000'
# Skip rest of the env validations
ENV SKIP_ENV_VALIDATION true
# Other env variables
ENV PORT 3000
ENV HOSTNAME 0.0.0.0

# Run webapp in dev mode
CMD ["devbox", "run", "pnpm", "dev:webapp"]