###############
# Run in Dev  #
###############

# Using devbox as base build image
FROM jetpackio/devbox:latest AS build-stage

# Installing your devbox project
WORKDIR /code
RUN mkdir -p /code && chown ${DEVBOX_USER}:${DEVBOX_USER} /code
USER ${DEVBOX_USER}:${DEVBOX_USER}
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} devbox.json devbox.json
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} devbox.lock devbox.lock
RUN devbox install
USER root:root

# Copy core files
COPY package.json nx.json pnpm-* go.* ./
COPY apps/subscriptions-job/go.* apps/subscriptions-job/
COPY apps/api-service/go.* apps/api-service/
COPY apps/expire-listings-job/go.* apps/expire-listings-job/
COPY libs/go-utils libs/go-utils
COPY libs/protos libs/protos

# Install dependencies
RUN devbox run pnpm install --frozen-lockfile
RUN devbox run go mod download

# Copy the go subscriptions-job source directory
COPY apps/subscriptions-job apps/subscriptions-job

# Build go subscriptions-job
ENV CGO_ENABLED 0
ENV GOOS linux

# Run subscriptions-job in dev mode
CMD ["devbox", "run", "pnpm", "dev:subscriptions-job"]