import { CountryMap } from "./types";

export const COUNTRIES: CountryMap = {
    AF: ["Afghanistan", "AFN", "؋", "93", "🇦🇫"],
    AX: ["Aland Islands", "EUR", "€", "+358-18", "🇦🇽"],
    AL: ["Albania", "ALL", "Lek", "355", "🇦🇱"],
    DZ: ["Algeria", "DZD", "دج", "213", "🇩🇿"],
    AS: ["American Samoa", "USD", "$", "+1-684", "🇦🇸"],
    AD: ["Andorra", "EUR", "€", "376", "🇦🇩"],
    AO: ["Angola", "AOA", "Kz", "244", "🇦🇴"],
    AI: ["Anguilla", "XCD", "$", "+1-264", "🇦🇮"],
    AQ: ["Antarctica", "AAD", "$", "672", "🇦🇶"],
    AG: ["Antigua And Barbuda", "XCD", "$", "+1-268", "🇦🇬"],
    AR: ["Argentina", "ARS", "$", "54", "🇦🇷"],
    AM: ["Armenia", "AMD", "֏", "374", "🇦🇲"],
    AW: ["Aruba", "AWG", "ƒ", "297", "🇦🇼"],
    AU: ["Australia", "AUD", "$", "61", "🇦🇺"],
    AT: ["Austria", "EUR", "€", "43", "🇦🇹"],
    AZ: ["Azerbaijan", "AZN", "m", "994", "🇦🇿"],
    BH: ["Bahrain", "BHD", ".د.ب", "973", "🇧🇭"],
    BD: ["Bangladesh", "BDT", "৳", "880", "🇧🇩"],
    BB: ["Barbados", "BBD", "Bds$", "+1-246", "🇧🇧"],
    BY: ["Belarus", "BYN", "Br", "375", "🇧🇾"],
    BE: ["Belgium", "EUR", "€", "32", "🇧🇪"],
    BZ: ["Belize", "BZD", "$", "501", "🇧🇿"],
    BJ: ["Benin", "XOF", "CFA", "229", "🇧🇯"],
    BM: ["Bermuda", "BMD", "$", "+1-441", "🇧🇲"],
    BT: ["Bhutan", "BTN", "Nu.", "975", "🇧🇹"],
    BO: ["Bolivia", "BOB", "Bs.", "591", "🇧🇴"],
    BQ: ["Bonaire, Sint Eustatius and Saba", "USD", "$", "599", "🇧🇶"],
    BA: ["Bosnia and Herzegovina", "BAM", "KM", "387", "🇧🇦"],
    BW: ["Botswana", "BWP", "P", "267", "🇧🇼"],
    BV: ["Bouvet Island", "NOK", "kr", "0055", "🇧🇻"],
    BR: ["Brazil", "BRL", "R$", "55", "🇧🇷"],
    IO: ["British Indian Ocean Territory", "USD", "$", "246", "🇮🇴"],
    BN: ["Brunei", "BND", "B$", "673", "🇧🇳"],
    BG: ["Bulgaria", "BGN", "Лв.", "359", "🇧🇬"],
    BF: ["Burkina Faso", "XOF", "CFA", "226", "🇧🇫"],
    BI: ["Burundi", "BIF", "FBu", "257", "🇧🇮"],
    KH: ["Cambodia", "KHR", "KHR", "855", "🇰🇭"],
    CM: ["Cameroon", "XAF", "FCFA", "237", "🇨🇲"],
    CA: ["Canada", "CAD", "$", "1", "🇨🇦"],
    CV: ["Cape Verde", "CVE", "$", "238", "🇨🇻"],
    KY: ["Cayman Islands", "KYD", "$", "+1-345", "🇰🇾"],
    CF: ["Central African Republic", "XAF", "FCFA", "236", "🇨🇫"],
    TD: ["Chad", "XAF", "FCFA", "235", "🇹🇩"],
    CL: ["Chile", "CLP", "$", "56", "🇨🇱"],
    CN: ["China", "CNY", "¥", "86", "🇨🇳"],
    CX: ["Christmas Island", "AUD", "$", "61", "🇨🇽"],
    CC: ["Cocos (Keeling) Islands", "AUD", "$", "61", "🇨🇨"],
    CO: ["Colombia", "COP", "$", "57", "🇨🇴"],
    KM: ["Comoros", "KMF", "CF", "269", "🇰🇲"],
    CG: ["Congo", "XAF", "FC", "242", "🇨🇬"],
    CK: ["Cook Islands", "NZD", "$", "682", "🇨🇰"],
    CR: ["Costa Rica", "CRC", "₡", "506", "🇨🇷"],
    CI: ["Cote D'Ivoire (Ivory Coast)", "XOF", "CFA", "225", "🇨🇮"],
    HR: ["Croatia", "HRK", "kn", "385", "🇭🇷"],
    CU: ["Cuba", "CUP", "$", "53", "🇨🇺"],
    CW: ["Curaçao", "ANG", "ƒ", "599", "🇨🇼"],
    CY: ["Cyprus", "EUR", "€", "357", "🇨🇾"],
    CZ: ["Czech Republic", "CZK", "Kč", "420", "🇨🇿"],
    CD: ["Democratic Republic of the Congo", "CDF", "FC", "243", "🇨🇩"],
    DK: ["Denmark", "DKK", "Kr.", "45", "🇩🇰"],
    DJ: ["Djibouti", "DJF", "Fdj", "253", "🇩🇯"],
    DM: ["Dominica", "XCD", "$", "+1-767", "🇩🇲"],
    DO: ["Dominican Republic", "DOP", "$", "+1-809 and 1-829", "🇩🇴"],
    TL: ["East Timor", "USD", "$", "670", "🇹🇱"],
    EC: ["Ecuador", "USD", "$", "593", "🇪🇨"],
    EG: ["Egypt", "EGP", "ج.م", "20", "🇪🇬"],
    SV: ["El Salvador", "USD", "$", "503", "🇸🇻"],
    GQ: ["Equatorial Guinea", "XAF", "FCFA", "240", "🇬🇶"],
    ER: ["Eritrea", "ERN", "Nfk", "291", "🇪🇷"],
    EE: ["Estonia", "EUR", "€", "372", "🇪🇪"],
    ET: ["Ethiopia", "ETB", "Nkf", "251", "🇪🇹"],
    FK: ["Falkland Islands", "FKP", "£", "500", "🇫🇰"],
    FO: ["Faroe Islands", "DKK", "Kr.", "298", "🇫🇴"],
    FJ: ["Fiji Islands", "FJD", "FJ$", "679", "🇫🇯"],
    FI: ["Finland", "EUR", "€", "358", "🇫🇮"],
    FR: ["France", "EUR", "€", "33", "🇫🇷"],
    GF: ["French Guiana", "EUR", "€", "594", "🇬🇫"],
    PF: ["French Polynesia", "XPF", "₣", "689", "🇵🇫"],
    TF: ["French Southern Territories", "EUR", "€", "262", "🇹🇫"],
    GA: ["Gabon", "XAF", "FCFA", "241", "🇬🇦"],
    GM: ["Gambia The", "GMD", "D", "220", "🇬🇲"],
    GE: ["Georgia", "GEL", "ლ", "995", "🇬🇪"],
    DE: ["Germany", "EUR", "€", "49", "🇩🇪"],
    GH: ["Ghana", "GHS", "GH₵", "233", "🇬🇭"],
    GI: ["Gibraltar", "GIP", "£", "350", "🇬🇮"],
    GR: ["Greece", "EUR", "€", "30", "🇬🇷"],
    GL: ["Greenland", "DKK", "Kr.", "299", "🇬🇱"],
    GD: ["Grenada", "XCD", "$", "+1-473", "🇬🇩"],
    GP: ["Guadeloupe", "EUR", "€", "590", "🇬🇵"],
    GU: ["Guam", "USD", "$", "+1-671", "🇬🇺"],
    GT: ["Guatemala", "GTQ", "Q", "502", "🇬🇹"],
    GG: ["Guernsey and Alderney", "GBP", "£", "+44-1481", "🇬🇬"],
    GN: ["Guinea", "GNF", "FG", "224", "🇬🇳"],
    GW: ["Guinea-Bissau", "XOF", "CFA", "245", "🇬🇼"],
    GY: ["Guyana", "GYD", "$", "592", "🇬🇾"],
    HT: ["Haiti", "HTG", "G", "509", "🇭🇹"],
    HM: ["Heard Island and McDonald Islands", "AUD", "$", "672", "🇭🇲"],
    HN: ["Honduras", "HNL", "L", "504", "🇭🇳"],
    HK: ["Hong Kong S.A.R.", "HKD", "$", "852", "🇭🇰"],
    HU: ["Hungary", "HUF", "Ft", "36", "🇭🇺"],
    IS: ["Iceland", "ISK", "kr", "354", "🇮🇸"],
    IN: ["India", "INR", "₹", "91", "🇮🇳"],
    ID: ["Indonesia", "IDR", "Rp", "62", "🇮🇩"],
    IR: ["Iran", "IRR", "﷼", "98", "🇮🇷"],
    IQ: ["Iraq", "IQD", "د.ع", "964", "🇮🇶"],
    IE: ["Ireland", "EUR", "€", "353", "🇮🇪"],
    IL: ["Israel", "ILS", "₪", "972", "🇮🇱"],
    IT: ["Italy", "EUR", "€", "39", "🇮🇹"],
    JM: ["Jamaica", "JMD", "J$", "+1-876", "🇯🇲"],
    JP: ["Japan", "JPY", "¥", "81", "🇯🇵"],
    JE: ["Jersey", "GBP", "£", "+44-1534", "🇯🇪"],
    JO: ["Jordan", "JOD", "ا.د", "962", "🇯🇴"],
    KZ: ["Kazakhstan", "KZT", "лв", "7", "🇰🇿"],
    KE: ["Kenya", "KES", "KSh", "254", "🇰🇪"],
    KI: ["Kiribati", "AUD", "$", "686", "🇰🇮"],
    XK: ["Kosovo", "EUR", "€", "383", "🇽🇰"],
    KW: ["Kuwait", "KWD", "ك.د", "965", "🇰🇼"],
    KG: ["Kyrgyzstan", "KGS", "лв", "996", "🇰🇬"],
    LA: ["Laos", "LAK", "₭", "856", "🇱🇦"],
    LV: ["Latvia", "EUR", "€", "371", "🇱🇻"],
    LB: ["Lebanon", "LBP", "£", "961", "🇱🇧"],
    LS: ["Lesotho", "LSL", "L", "266", "🇱🇸"],
    LR: ["Liberia", "LRD", "$", "231", "🇱🇷"],
    LY: ["Libya", "LYD", "د.ل", "218", "🇱🇾"],
    LI: ["Liechtenstein", "CHF", "CHf", "423", "🇱🇮"],
    LT: ["Lithuania", "EUR", "€", "370", "🇱🇹"],
    LU: ["Luxembourg", "EUR", "€", "352", "🇱🇺"],
    MO: ["Macau S.A.R.", "MOP", "$", "853", "🇲🇴"],
    MG: ["Madagascar", "MGA", "Ar", "261", "🇲🇬"],
    MW: ["Malawi", "MWK", "MK", "265", "🇲🇼"],
    MY: ["Malaysia", "MYR", "RM", "60", "🇲🇾"],
    MV: ["Maldives", "MVR", "Rf", "960", "🇲🇻"],
    ML: ["Mali", "XOF", "CFA", "223", "🇲🇱"],
    MT: ["Malta", "EUR", "€", "356", "🇲🇹"],
    IM: ["Man (Isle of)", "GBP", "£", "+44-1624", "🇮🇲"],
    MH: ["Marshall Islands", "USD", "$", "692", "🇲🇭"],
    MQ: ["Martinique", "EUR", "€", "596", "🇲🇶"],
    MR: ["Mauritania", "MRO", "MRU", "222", "🇲🇷"],
    MU: ["Mauritius", "MUR", "₨", "230", "🇲🇺"],
    YT: ["Mayotte", "EUR", "€", "262", "🇾🇹"],
    MX: ["Mexico", "MXN", "$", "52", "🇲🇽"],
    FM: ["Micronesia", "USD", "$", "691", "🇫🇲"],
    MD: ["Moldova", "MDL", "L", "373", "🇲🇩"],
    MC: ["Monaco", "EUR", "€", "377", "🇲🇨"],
    MN: ["Mongolia", "MNT", "₮", "976", "🇲🇳"],
    ME: ["Montenegro", "EUR", "€", "382", "🇲🇪"],
    MS: ["Montserrat", "XCD", "$", "+1-664", "🇲🇸"],
    MA: ["Morocco", "MAD", "DH", "212", "🇲🇦"],
    MZ: ["Mozambique", "MZN", "MT", "258", "🇲🇿"],
    MM: ["Myanmar", "MMK", "K", "95", "🇲🇲"],
    NA: ["Namibia", "NAD", "$", "264", "🇳🇦"],
    NR: ["Nauru", "AUD", "$", "674", "🇳🇷"],
    NP: ["Nepal", "NPR", "₨", "977", "🇳🇵"],
    NL: ["Netherlands", "EUR", "€", "31", "🇳🇱"],
    NC: ["New Caledonia", "XPF", "₣", "687", "🇳🇨"],
    NZ: ["New Zealand", "NZD", "$", "64", "🇳🇿"],
    NI: ["Nicaragua", "NIO", "C$", "505", "🇳🇮"],
    NE: ["Niger", "XOF", "CFA", "227", "🇳🇪"],
    NG: ["Nigeria", "NGN", "₦", "234", "🇳🇬"],
    NU: ["Niue", "NZD", "$", "683", "🇳🇺"],
    NF: ["Norfolk Island", "AUD", "$", "672", "🇳🇫"],
    KP: ["North Korea", "KPW", "₩", "850", "🇰🇵"],
    MK: ["North Macedonia", "MKD", "ден", "389", "🇲🇰"],
    MP: ["Northern Mariana Islands", "USD", "$", "+1-670", "🇲🇵"],
    NO: ["Norway", "NOK", "kr", "47", "🇳🇴"],
    OM: ["Oman", "OMR", ".ع.ر", "968", "🇴🇲"],
    PK: ["Pakistan", "PKR", "₨", "92", "🇵🇰"],
    PW: ["Palau", "USD", "$", "680", "🇵🇼"],
    PS: ["Palestinian Territory Occupied", "ILS", "₪", "970", "🇵🇸"],
    PA: ["Panama", "PAB", "B/.", "507", "🇵🇦"],
    PG: ["Papua new Guinea", "PGK", "K", "675", "🇵🇬"],
    PY: ["Paraguay", "PYG", "₲", "595", "🇵🇾"],
    PE: ["Peru", "PEN", "S/.", "51", "🇵🇪"],
    PH: ["Philippines", "PHP", "₱", "63", "🇵🇭"],
    PN: ["Pitcairn Island", "NZD", "$", "870", "🇵🇳"],
    PL: ["Poland", "PLN", "zł", "48", "🇵🇱"],
    PT: ["Portugal", "EUR", "€", "351", "🇵🇹"],
    PR: ["Puerto Rico", "USD", "$", "+1-787 and 1-939", "🇵🇷"],
    QA: ["Qatar", "QAR", "ق.ر", "974", "🇶🇦"],
    RE: ["Reunion", "EUR", "€", "262", "🇷🇪"],
    RO: ["Romania", "RON", "lei", "40", "🇷🇴"],
    RU: ["Russia", "RUB", "₽", "7", "🇷🇺"],
    RW: ["Rwanda", "RWF", "FRw", "250", "🇷🇼"],
    SH: ["Saint Helena", "SHP", "£", "290", "🇸🇭"],
    KN: ["Saint Kitts And Nevis", "XCD", "$", "+1-869", "🇰🇳"],
    LC: ["Saint Lucia", "XCD", "$", "+1-758", "🇱🇨"],
    PM: ["Saint Pierre and Miquelon", "EUR", "€", "508", "🇵🇲"],
    VC: ["Saint Vincent And The Grenadines", "XCD", "$", "+1-784", "🇻🇨"],
    BL: ["Saint-Barthelemy", "EUR", "€", "590", "🇧🇱"],
    MF: ["Saint-Martin (French part)", "EUR", "€", "590", "🇲🇫"],
    WS: ["Samoa", "WST", "SAT", "685", "🇼🇸"],
    SM: ["San Marino", "EUR", "€", "378", "🇸🇲"],
    ST: ["Sao Tome and Principe", "STD", "Db", "239", "🇸🇹"],
    SA: ["Saudi Arabia", "SAR", "﷼", "966", "🇸🇦"],
    SN: ["Senegal", "XOF", "CFA", "221", "🇸🇳"],
    RS: ["Serbia", "RSD", "din", "381", "🇷🇸"],
    SC: ["Seychelles", "SCR", "SRe", "248", "🇸🇨"],
    SL: ["Sierra Leone", "SLL", "Le", "232", "🇸🇱"],
    SG: ["Singapore", "SGD", "$", "65", "🇸🇬"],
    SX: ["Sint Maarten (Dutch part)", "ANG", "ƒ", "1721", "🇸🇽"],
    SK: ["Slovakia", "EUR", "€", "421", "🇸🇰"],
    SI: ["Slovenia", "EUR", "€", "386", "🇸🇮"],
    SB: ["Solomon Islands", "SBD", "Si$", "677", "🇸🇧"],
    SO: ["Somalia", "SOS", "Sh.so.", "252", "🇸🇴"],
    ZA: ["South Africa", "ZAR", "R", "27", "🇿🇦"],
    GS: ["South Georgia", "GBP", "£", "500", "🇬🇸"],
    KR: ["South Korea", "KRW", "₩", "82", "🇰🇷"],
    SS: ["South Sudan", "SSP", "£", "211", "🇸🇸"],
    ES: ["Spain", "EUR", "€", "34", "🇪🇸"],
    LK: ["Sri Lanka", "LKR", "Rs", "94", "🇱🇰"],
    SD: ["Sudan", "SDG", ".س.ج", "249", "🇸🇩"],
    SR: ["Suriname", "SRD", "$", "597", "🇸🇷"],
    SJ: ["Svalbard And Jan Mayen Islands", "NOK", "kr", "47", "🇸🇯"],
    SZ: ["Swaziland", "SZL", "E", "268", "🇸🇿"],
    SE: ["Sweden", "SEK", "kr", "46", "🇸🇪"],
    CH: ["Switzerland", "CHF", "CHf", "41", "🇨🇭"],
    SY: ["Syria", "SYP", "LS", "963", "🇸🇾"],
    TW: ["Taiwan", "TWD", "$", "886", "🇹🇼"],
    TJ: ["Tajikistan", "TJS", "SM", "992", "🇹🇯"],
    TZ: ["Tanzania", "TZS", "TSh", "255", "🇹🇿"],
    TH: ["Thailand", "THB", "฿", "66", "🇹🇭"],
    BS: ["The Bahamas", "BSD", "B$", "+1-242", "🇧🇸"],
    TG: ["Togo", "XOF", "CFA", "228", "🇹🇬"],
    TK: ["Tokelau", "NZD", "$", "690", "🇹🇰"],
    TO: ["Tonga", "TOP", "$", "676", "🇹🇴"],
    TT: ["Trinidad And Tobago", "TTD", "$", "+1-868", "🇹🇹"],
    TN: ["Tunisia", "TND", "ت.د", "216", "🇹🇳"],
    TR: ["Turkey", "TRY", "₺", "90", "🇹🇷"],
    TM: ["Turkmenistan", "TMT", "T", "993", "🇹🇲"],
    TC: ["Turks And Caicos Islands", "USD", "$", "+1-649", "🇹🇨"],
    TV: ["Tuvalu", "AUD", "$", "688", "🇹🇻"],
    UG: ["Uganda", "UGX", "USh", "256", "🇺🇬"],
    UA: ["Ukraine", "UAH", "₴", "380", "🇺🇦"],
    AE: ["United Arab Emirates", "AED", "إ.د", "971", "🇦🇪"],
    GB: ["United Kingdom", "GBP", "£", "44", "🇬🇧"],
    US: ["United States", "USD", "$", "1", "🇺🇸"],
    UM: ["United States Minor Outlying Islands", "USD", "$", "1", "🇺🇲"],
    UY: ["Uruguay", "UYU", "$", "598", "🇺🇾"],
    UZ: ["Uzbekistan", "UZS", "лв", "998", "🇺🇿"],
    VU: ["Vanuatu", "VUV", "VT", "678", "🇻🇺"],
    VA: ["Vatican City State (Holy See)", "EUR", "€", "379", "🇻🇦"],
    VE: ["Venezuela", "VES", "Bs", "58", "🇻🇪"],
    VN: ["Vietnam", "VND", "₫", "84", "🇻🇳"],
    VG: ["Virgin Islands (British)", "USD", "$", "+1-284", "🇻🇬"],
    VI: ["Virgin Islands (US)", "USD", "$", "+1-340", "🇻🇮"],
    WF: ["Wallis And Futuna Islands", "XPF", "₣", "681", "🇼🇫"],
    EH: ["Western Sahara", "MAD", "MAD", "212", "🇪🇭"],
    YE: ["Yemen", "YER", "﷼", "967", "🇾🇪"],
    ZM: ["Zambia", "ZMW", "ZK", "260", "🇿🇲"],
    ZW: ["Zimbabwe", "ZWL", "$", "263", "🇿🇼"],
};
